name: Build

on:
  [push]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, linux, windows]
        arch: [amd64]
        include:
          - os: darwin
            arch: arm64
          - os: windows
            exe: ".exe"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: go get .
      - name: Build ${{ matrix.os }}/${{matrix.arch}}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: go build -o keyboard_layout_calculator_${{ matrix.os }}_${{matrix.arch}}${{matrix.exe}}
      - name: Upload bins
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: keyboard_layout_calculator_${{ matrix.os }}_${{matrix.arch}}${{matrix.exe}}
