name: Build

on:
  push:
    tags: ["v**"]

jobs:
  build_cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, linux, windows]
        arch: [amd64]
        include:
          - os: darwin
            arch: arm64
          - os: windows
            exe: ".exe"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: cli/go.mod
          cache-dependency-path: cli/go.sum
      - name: Install dependencies common
        run: go get .
        working-directory: common 
      - name: Install dependencies cli
        run: go get .
        working-directory: cli
      - name: Build ${{ matrix.os }}/${{matrix.arch}}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: go build -o ../keyboard_layout_calculator_${{ matrix.os }}_${{matrix.arch}}${{matrix.exe}}
        working-directory: cli
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body: "release"
          files: keyboard_layout_calculator_${{ matrix.os }}_${{matrix.arch}}${{matrix.exe}}
  build_gui:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
        arch: [amd64]
        include:
          - platform: macos-latest
            os: darwin
          - platform: macos-latest
            arch: arm64
            os: darwin
          - platform: windows-latest
            os: windows
          - platform: ubuntu-latest
            os: linux
    uses: ./.github/workflows/build_gui_${{matrix.os}}.yaml
    with:
      platform: ${{matrix.platform}}
      os: ${{matrix.os}}
      arch: ${{matrix.arch}}